name: Build vulndb

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  schedule:
    # Run once daily
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Publish vulndb OCI artifact

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Log in to the container registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        env:
          INPUT_GITHUB_ACTOR: ${{ github.actor }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run tools/vulndb/*.go
