name: GitHub Actions Security Analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
      - .github/actions/**/*.yaml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/zizmor.yaml
      - .github/workflows/**/*.yaml
      - .github/actions/**/*.yaml
  schedule:
    # Some random-ish cron to help with GitHub Actions scheduling, once a week
    - cron: 29 11 * * 2

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Write events
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          persona: pedantic
          version: v1.16.0
